
spring:
  redis:
    pool.max-idle: 10
    pool.max-active: 10
    pool.min-idle: 5
    pool.max-wait: 2000
    timeout: 5000
    host: 192.168.1.1
    password: 123456
    port: 6379
    database: 0
server:
  port: 1001